### ISSUE TITLE
jaclang Installation issue - Mac

### ISSUE THREAD

**Issue by Sarujan1999** [Jaseci-Labs/jaclang#103]
failed to run-screenshots of the error  is attached below,
<img width="1512" alt="Screenshot 2023-12-06 at 02 33 43" src="https://github.com/Jaseci-Labs/jaclang/assets/129873512/4990b843-c1b5-4c0d-8a60-5c5dd26373e8">
<img width="1512" alt="Screenshot 2023-12-06 at 02 41 36" src="https://github.com/Jaseci-Labs/jaclang/assets/129873512/1076ebb5-2b24-4f85-9a2d-530c3644ac4b">
<img width="1512" alt="Screenshot 2023-12-06 at 02 41 48" src="https://github.com/Jaseci-Labs/jaclang/assets/129873512/84b43d5c-deca-44f8-b7a7-077c11aba47a">

**Comment by marsninja** [comment]
The commit https://github.com/Jaseci-Labs/jaclang/commit/cb614870bb0f37b98196265f24a55c9c7b844a52 resolved this issue.

Was related to something going wrong with the package build and push to pypi. This has been QA tested, not immediately obvious how to create a unit test for this.

**Comment by marsninja** [comment]
Fixed some time ago.
