### ISSUE TITLE
Installation issue - Windows

### ISSUE THREAD

**Issue by kugesan2000** [Jaseci-Labs/jaclang#104]
Encountered the following issue while installing jaclang and try jac run test.jac; for 10.8,11,12 

[Issue slide in Detail link](https://docs.google.com/presentation/d/14LijnUXHbKsGOspn2Khakh41uSQkUzHTpWh6lO77sMA/edit?usp=sharing)

![image](https://github.com/Jaseci-Labs/jaclang/assets/129170533/afe679e3-76b7-4e15-b5fa-f7110597d268)

**Comment by marsninja** [comment]
The commit cb61487 resolved this issue.

Was related to something going wrong with the package build and push to pypi. This has been QA tested, not immediately obvious how to create a unit test for this.

**Comment by marsninja** [comment]
Fixed some time ago.
