### ISSUE TITLE
Could use a diagram for cleaner example in spec

### ISSUE THREAD

**Issue by marsninja** [Jaseci-Labs/jaclang#13]
Could use a nice diagram to illustrate the cleaner example, I imagine one half of the diagram showing a graph overlaying rooms to clean with a cleaner as a walker on a node, and the other side showing some kind of ridiculous situation where rooms are being torn apart to send to a cleaning function, could be two figures.  Should be inserted somewhere here: 
https://github.com/Jaseci-Labs/jaseci2/blob/4868a406936db0be1a8e0552e7a798137441cc15/docs/docs/internals/spec/arch.md?plain=1#L21-L35

**Comment by ypkang** [comment]
I can knock this one out. @marsninja

**Comment by marsninja** [comment]
Old and irrelevant.
