### ISSUE TITLE
unpack_expressions.jac

### ISSUE THREAD

**Issue by kugesan1105** [Jaseci-Labs/jaclang#160]
-  for list 
         output should be  [1, 2, 3, 4, 5,5, 8, 7, 6, 9] but t is [[1, 2, 3, 4, 5], [5, 8, 7, 6, 9]]

- for dictionary 
        currently it is not generate error  
### JAC
![image](https://github.com/Jaseci-Labs/jaclang/assets/153247429/d2cf3a07-77b5-4fb5-a4d0-b46e961c30a6)
### PYTHON
![image](https://github.com/Jaseci-Labs/jaclang/assets/153247429/665a398d-5719-46d9-8d86-230e036abb84)

**Comment by marsninja** [comment]
Fixed with commit 031d699
