### ISSUE TITLE
Awesome Looking Refactoring `.impl.jac` and `.test.jac`

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#164]
Currently, in jaclang we have the ability to use implementations to make the code easily refactorable. But, the current file naming convention is not looking good. So I propose 2 new file extensions to the game. (`.impl.jac` and `.test.jac`)

Inspiration is taken from the Vue.js, React.js and Some other JS Libraries.

Things that make the languages more good looking and easy
1. After this change the users will be able to identify the test files and impls clearly as the vscode extension can make those file icons look different
2. User doesn't need to import the imp to the original file (Need to use the same filename `<something>.jac` and `<something>.impl.jac`)
3. Ability for the plugins and jac cli to identify tests easily
4. When compiling, compiler can easily find the relevant impl files for a particular jac file.

**Comment by marsninja** [comment]
This is a very nice feature request! It was implemented with #183
