### ISSUE TITLE
Multiline string as arguments

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#165]
As we are using `"""<Somthing>"""` as comments in language. we cannot use a multi-string as an argument.

#### Code to Reproduce the Error
Working Implementation. But the code line is long. not suitable.
```jaclang
can function(long_line:str) -> None {
    print(long_line);
}

with entry {
    function("This is a long line of code. Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah")
}
```
Error Implementation
```jaclang
can function(long_line:str) -> None {
    print(long_line);
}

with entry {
    function("""This is a long line of code. Blah Blah Blah Blah Blah Blah Blah 
    Blah Blah Blah Blah Blah Blah Blah Blah Blah""")
}
```

This is important for the formatting too.

**Comment by marsninja** [comment]
Fixed with [06e1ec8](https://github.com/Jaseci-Labs/jaclang/commit/06e1ec8568f31840bc05278cc52ba783ee3cf6db)
