### ISSUE TITLE
Relative Import Failing

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#168]
![Screenshot 2024-01-23 at 05 34 48](https://github.com/Jaseci-Labs/jaclang/assets/52673571/f78d5555-6965-4864-b729-d09bdc7ada2b)
When generator_impl.jac imported in the generator.jac it doesn't find the impl file and fails to compile.
![Screenshot 2024-01-23 at 05 34 14](https://github.com/Jaseci-Labs/jaclang/assets/52673571/95e92daf-55b7-42c8-8f0e-2e58d35123ff)
When added the components. in front of the generator_impl compiler finds the file and fills the implementations but error comes in the execution as __jac_import__ tries to import impl from componenets/components.

**Comment by marsninja** [comment]
Hi @chandralegend , This was recently implemented and merged into main via #199 

Could be more thoroughly tested though, closing for now, but feel free to throw a test in and let me know if you have any issues and I can reopen.
