### ISSUE TITLE
Async Ability Issue

### ISSUE THREAD

**Issue by amadolid** [Jaseci-Labs/jaclang#201]
![image](https://github.com/Jaseci-Labs/jaclang/assets/74129725/dd5249e5-df65-4e11-9aed-5e5715f73fd4)
![image](https://github.com/Jaseci-Labs/jaclang/assets/74129725/4fb6893b-df46-411a-8e23-0931fbbf103f)

**Comment by marsninja** [comment]
Should be fixed in [2a6988f](https://github.com/Jaseci-Labs/jaclang/commit/2a6988fc0c72f1910ffff62e1ca60752e3e6ab88)  

Try it @amadolid  and let me know then I'll close
