### ISSUE TITLE
Auto API Generation

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#207]
This is something that goes along with the plugin.

Problem with Jaseci v1 Approach of API generation
- No separate API Endpoints & No API Documentation for each action (e.g. - assuming you have an ability you want to convert into an API endpoint, you have to use the default API and mention the name of the ability or walker to run it). 

Possibile Implementation
For a jac file if we have included the jac plugin auto_api. Every walker , ability will become an API endpoint.

```jac
include:plugin auto_api;
include:plugin from auto_api, ignore;

can test1;
@ignore
can test2;
```

Above code will create only one API Endpoint (test1) and test2 will not be made.

**Comment by marsninja** [comment]
Love this, will save for roadmap.

**Comment by marsninja** [comment]
Btw, I think it would be best to leverage the public/private/protected access modifiers to do this. We'll need to pass this info through the make_arch interface. And need to add one for abilities. 

This is a note to self and perhaps @amadolid

**Comment by ypkang** [comment]
Close this for now and we will revisit when we have a v1 of the jaseci stack.
