### ISSUE TITLE
Nested node connect doesn't connect on sequence

### ISSUE THREAD

**Issue by amadolid** [Jaseci-Labs/jaclang#214]
```js
walker post_no_body {
    can enter with `<r> entry {
        b = boy(val1="a", val2="b");
        g = girl(val="b");
        <r> ++> b ++> g;
        <r>.save();
        return True;
    }
}
```

connection will be created like this
<r> ++> b
<r> ++> g

but in developer perspective it should be
<r> ++> b
b ++> g

current implementation
![image](https://github.com/Jaseci-Labs/jaclang/assets/74129725/73a95ae6-a610-4626-b52a-d0390a09b066)

**Comment by marsninja** [comment]
Fixed #219
