### ISSUE TITLE
[BUG] : Jaclang init() cannot distinguish between __init__() and init() in pygame 

### ISSUE THREAD

**Issue by Jayanaka-98** [Jaseci-Labs/jaclang#259]
**Describe the bug**
When the RPG game is executed the following error occurs.
![image](https://github.com/Jaseci-Labs/jaclang/assets/110921856/63d71c6b-9761-4b99-bf0b-76da2dd63842)
Here pygame.init() does not intend to run `__init__` on pygame object. pygame.init() is just a defined function. 

**To Reproduce**
In terminal (on main):
`cd examples/rpg_game/jac_impl/jac_impl_3/ `
`jac run main.jac` 

**Jaclang/Python Version**
Python 3.11.3 and Jac installed from source.

**Screen Cap.**
![image](https://github.com/Jaseci-Labs/jaclang/assets/110921856/9405a056-ef29-4e73-a7b1-9705afbaec58)

**Comment by marsninja** [comment]
Hi @Jayanaka-98 , have the keyword escape feature of Jac solves this. 

Use
```
pygame.<>init(); 
```
