### ISSUE TITLE
[BUG] Body not found when the same KW in the impl file

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#264]
**Describe the bug**
Body was not found when the same KW in the impl file. Seems like the FunctionDef is trying to get from `math` KW in the import.

**To Reproduce**
```jac
#test.jac
can math; 
```
```jac
#test.impl.jac
from math import sqrt;
:can:math {
  return sqrt(4);
}
````

**Jaclang/Python Version**
Jaclang - 0.5.7
Python - 3.12
OS - Ubuntu 22.04

**Comment by marsninja** [comment]
Resolved in #270
