### ISSUE TITLE
[BUG] Relative Import above one directory not working

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#266]
**Describe the bug**
`import:jac from ..utils, something` doesnt work

**Comment by marsninja** [comment]
Hey chandra synatx like `from ..utils.helpers import pascal_to_snake` doesnt work in python either

**Comment by marsninja** [comment]
Huh interesting, we have a file `jaclang/jaclang/tests/fixtures/deep/deeper/snd_lev.jac` that has teh following code that works, is this what you wanted?

```
import:jac from ..mycode, code;

can slprint ->str {
    return "sl" + code();
}
```

**Comment by marsninja** [comment]
Close with #341
