### ISSUE TITLE
[FEATURE] Better Jac Test Arguments

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#279]
- [ ] `jac test -v test_*` will find all the `test_*.jac` files and run them one after another
- [ ] `jac test -x` will stop running tests as soon as finds an error
- [ ] `jac test` will run jac test for all the jac files in the directory
- [ ] `jac test -d src` runs tests for all the files in the src directory

**Comment by marsninja** [comment]
This is a great set of additions, @Sivasuthan9 you want to take it?

**Comment by Sivasuthan9** [comment]
@marsninja , @chandralegend , @ypkang 
Features added https://github.com/Jaseci-Labs/jaclang/pull/289
![image](https://github.com/Jaseci-Labs/jaclang/assets/153247727/9e494ecd-4f5e-48d1-8557-8a3e28caa746)
