### ISSUE TITLE
[BUG] Unable to Declare Enum Inside Architype

### ISSUE THREAD

**Issue by kugesan1105** [Jaseci-Labs/jaclang#284]
**Description**
When declaring an enum inside an architype in Jacang, it leads to an Internal Error .

**Code to Reproduce**
```
obj outer{
    has o1:int=9;

    obj inner{
        has i1:int=8;
    }
    can foo(){
        return 'foo';
    }
    enum color{
        red,
        green,
        blue
        }

}
```
**Screenshot**

![image](https://github.com/Jaseci-Labs/jaclang/assets/153247429/9f9bc90b-1e9e-43b2-98e5-a225d333b02e)

**Comment by Sivasuthan9** [comment]
@marsninja   
pr:https://github.com/Jaseci-Labs/jaclang/pull/319
