### ISSUE TITLE
[FEATURE] Update formatter to support semstring

### ISSUE THREAD

**Issue by ypkang** [Jaseci-Labs/jaclang#293]
We need to update the jac formatter to support the new semstring syntax.

https://github.com/Jaseci-Labs/jaclang/pull/282/checks

**Comment by kugesan1105** [comment]
[commit ](https://github.com/Jaseci-Labs/jaclang/pull/286/commits/9fff94b19638c0fc98892df24979cc35a838b62e)resolves it
