### ISSUE TITLE
Jot down Asim ideas in ideas markdown

### ISSUE THREAD

**Issue by marsninja** [Jaseci-Labs/jaclang#7]

**Comment by asimsalim** [comment]
1. Currently the starting point to use Jaseci is user. This would hamper adoption where a user management / IAM system is already existing. 
**Suggestion** I am proposing to convert user management as an optional module and enable starting point as graph root and sentinel which can be recorded in external systems using an access token. This behavior can be replicated using the current system by using a long TTL. But it is not a natural flow.

**Comment by asimsalim** [comment]
2. Realizing the full potential of Jaseci requires the ability to use a variety of Jaseci AI Kit modules as actions in JAC. However a barrier to this is the limitation of memory( in local ) or lack of devops skills ( in remote ). Jsorc also doesnt solve the problem of needing to resize a cluster with additional nodes ( if the default max node configuration is used ).  
**Suggestion** a. Enable the user to load hosted actions libraries with pre-trained models with a usage cap ( like hugging face APIs). 
                         b. Enable a pipeline for users to publish their trained models to either their own managed cluster / Jaseci hosted model management infra and use either while doing the load action.
